name: dw-tap
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- jupyterlab
- pip
- pandas
- geopandas
- pyproj
- numpy
- matplotlib
- seaborn
- scikit-learn
- tensorflow
- openpyxl
- windrose
- plotly
- pydeck
- tqdm
- fiona
- shapely
- scipy
- NREL-rex
- statsmodels
- pip:
  - h5pyd
  - rosely
  - kaleido
